title: İsmail Arıcıoğlu
#logo: /assets/img/headshot_circle.png
logo: /assets/img/headshot_circle_400.png
#logo: /assets/img/logo.png
description: Otodidaktik Mühendis Kafalı Yazılım Teknikeri
show_downloads: true
theme: jekyll-theme-minimal
